import pyautogui as py
import time
import os
def enter(): 
    py.press('enter')
    time.sleep(1)
    
def pressione(x):
    py.press(x)
    time.sleep(1)
    
def escreve(x):
    py.write(x)
    
def nomes(y):
    py.write(y)
    
def tab():
    py.press('5tab')
    
 
pressione('win')
time.sleep(1)
escreve('excel')
enter()
time.sleep(1)
enter()
escreve("LISTA DE CHAMADA :")
tab()
enter()

escreve("ALEXANDRE BAGINI:")
tab()
enter()
escreve("ALEXANDRE LEMES:")
tab()
enter()
escreve("ANA CAROLINE MORAES MALHEIRO:")
tab()
enter()
escreve("ANA JÚLIA FELISBERTO BUENO:")
tab()
enter()
escreve("ANDRE FELIPE ROSA DA SILVA:")
tab()
enter()
escreve("ARTHUR MATHEUS DE MOURA:")
tab()
enter()
escreve("CESAR AUGUSTO CAVALLARO:")
tab()
enter()
escreve("DIEGO DA ROZ OTAVIANO:")
tab()
enter()
escreve("ENZO BIASON MANHA:")
tab()
enter()
escreve("GABRIEL SOARES NECO:")
tab()
enter()
escreve("GIULIA DA CUNHA ROCHA:")
tab()
enter()
escreve("GUILHERME AUGUSTO DOS SANTOS SILVA:")
tab()
enter()
escreve("GUILHERME SOUZA LIMA:")
tab()
enter()
escreve("ISABELLE DANIEL DOS ANJOS:")
tab()
enter()
escreve("JOÃO PEDRO PORTOCARRERO:")
tab()
enter()
escreve("JÚLIA MONTEIRO DALLA VECCHIA:")
tab()
enter()
escreve("JULIANO SILVESTRE DIOGO:")
tab()
enter()
escreve("KAUÊ LIMA BARBOSA:")
tab()
enter()
escreve("LEONARDO RODRIGO CAETANO:")
tab()
enter()
escreve("LETÍCIA RODRIGUES DE PAIVA:")
tab()
enter()
escreve("MARIA EDUARDA DOS SANTOS:")
tab()
enter()
escreve("MIRELLA TURQUETI CORREA GONÇALVES:")
tab()
enter()
escreve("MURILO AUGUSTO CARNEIRO:")
tab()
enter()
escreve("NATÁLIA PAZ DA SILVA:")
tab()
enter()
escreve("NATALIA VAZ CERQUEIRA:")
tab()
enter()
escreve("NATHAN HENRIQUE DA CUNHA SOUZA:")
tab()
enter()
escreve("PABLO DA SILVA FERREIRA DE LIMA:")
tab()
enter()
escreve("RAFAELA FATIMA DE SOUZA ALVES:")
tab()
enter()
escreve("RUAN HENRIQUE PALMEIRA:")
tab()
enter()
escreve("THAINÁ CRISTINA DE SOUZA:")
tab()
enter()
escreve("VINICIUS DE OLIVEIRA MOURA:")
tab()
enter()
escreve("VINICIUS FANTINELLI:")
tab()
enter()
escreve("VÍTOR VINÍCIUS GONÇALVES:")
tab()
enter()
escreve("YURI AZEVEDO ANTUNES DE SOUZA:")
tab()
enter()


os.system("pause")
int(input("Digite a quantidade de pessoas presentes:"))
str(input("Digite todos nomes não presentes:"))




os.sytem("pause")